// Generated by IcedCoffeeScript 1.7.1-f
(function() {
  var controllers, web_interface;

  web_interface = angular.module("web_interface", ["ngSanitize"]);

  controllers = {};

  controllers.my_controller = function($scope, $http, $interval, $sanitize) {
    $scope.init_const = function() {
      $scope["const"] = {};
      $scope["const"].colors = {};
      $scope["const"].colors.host_alive = '#66FFCC';
      $scope["const"].colors.host_dead = '#FFCCCC';
      $scope["const"].colors.app_alive = '#33FF00';
      return $scope["const"].colors.app_dead = '#FF0000';
    };
    $scope.generate_host_style = function(status) {
      if (status === "alive") {
        return {
          'background-color': $scope["const"].colors.host_alive
        };
      } else {
        return {
          'background-color': $scope["const"].colors.host_dead
        };
      }
    };
    $scope.generate_app_style = function(status) {
      if (status === "alive") {
        return {
          'background-color': $scope["const"].colors.app_alive
        };
      } else {
        return {
          'background-color': $scope["const"].colors.app_dead
        };
      }
    };
    return $scope.init = function() {
      $scope.init_const();
      $scope.bullet = $.bullet("ws://" + location.host + "/bullet");
      $scope.bullet.onopen = function() {
        var mess;
        console.log("bullet: connected");
        mess = {
          "subject": "get_state",
          "content": "nil"
        };
        return $scope.bullet.send(JSON.stringify(mess));
      };
      $scope.bullet.ondisconnect = function() {
        return console.log("bullet: disconnected");
      };
      $scope.bullet.onclose = function() {
        return console.log("bullet: closed");
      };
      $scope.bullet.onmessage = function(e) {
        var mess;
        mess = $.parseJSON(e.data);
        if (mess.subject === "error") {
          alert(mess.content);
        }
        if (mess.subject === "pong") {
          "ok";
        }
        if (mess.subject === "refresh") {
          return $scope.state = mess.content;
        }
      };
      $scope.bullet.onheartbeat = function() {
        var mess;
        mess = {
          "subject": "ping",
          "content": "nil"
        };
        return $scope.bullet.send(JSON.stringify(mess));
      };
      return $interval((function() {}), 500, [], []);
    };
  };

  web_interface.controller(controllers);

}).call(this);
